http:
  middlewares:
    authelia:
      forwardAuth:
        address: "http://authelia:9091/api/authz/forward-auth?authelia_url=https://auth.coma.henriksen.es"
        trustForwardHeader: false
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"
          - "Remote-Name"
          - "Remote-Email"

    crowdsec:
      forwardAuth:
        address: "http://crowdsec-bouncer:8080/api/v1/forwardAuth"
        trustForwardHeader: true

    secure:
      chain:
        middlewares:
          - crowdsec
          - authelia
